모집공고 상태 자동변경 로직 작성 완료
KGU-C-Lab/clab-server pull request #389
Opened 2024-06-24 15:50 UTC by SongJaeHoonn

## Summary

> #353

원래 모집 공고의 상태를 직접 String으로 수정해야 하는 문제점이 있었습니다.
따라서 모집 시작 시각, 모집 종료 시각을 기준으로 모집 공고의 상태를 자동으로 변경하는 로직을 구현했습니다.

## Tasks

- 모집 공고 상태 enum 마련
- 모집 공고 상태 자동 변경 스케줄링 구현

## ETC

스케줄링을 사용하는 로직에서 Transaction 어노테이션을 적용하면, 변경 객체가 준영속상태가 되는 문제가 있었습니다.
따라서 스케줄링 로직과 Transaction 어노테이션이 동시에 돌아가지 않는 이슈로 인해 직접 객체의 변경 사항을 커밋했습니다.

## Screenshot

*현재시각 < 모집 시작시각*
![스크린샷 2024-06-24 233354](https://github.com/KGU-C-Lab/clab-server/assets/128021502/cbd17fdc-9a25-4dc8-860e-976427a53f3a)

*모집 시작시각 < 현재시각 < 모집 종료시각*
![스크린샷 2024-06-24 233705](https://github.com/KGU-C-Lab/clab-server/assets/128021502/16d1a8be-7902-4c1e-afd9-92e87b191b66)

*현재시각 > 모집 종료시각*
![스크린샷 2024-06-25 000214](https://github.com/KGU-C-Lab/clab-server/assets/128021502/e3381ff7-bb90-4afe-8fd1-699c74680b26)

*모집공고 조회*
![스크린샷 2024-06-25 004438](https://github.com/KGU-C-Lab/clab-server/assets/128021502/88a48bb2-537b-4927-b678-d6dcd273f89d)

*모집공고 일정 수정 전*
![스크린샷 2024-06-25 212236](https://github.com/KGU-C-Lab/clab-server/assets/128021502/8ceee374-0e71-4006-82d1-f32d4586a4ab)
![스크린샷 2024-06-25 212328](https://github.com/KGU-C-Lab/clab-server/assets/128021502/10070fc4-326b-46dc-9caa-f61cddd6df05)
![스크린샷 2024-06-25 212432](https://github.com/KGU-C-Lab/clab-server/assets/128021502/962f15e6-821e-4232-8c31-f4cb23584fe5)

*모집공고 일정 수정 후(기간 연장)*
![스크린샷 2024-06-25 212625](https://github.com/KGU-C-Lab/clab-server/assets/128021502/4c8de498-d50e-4348-9cef-325085406fa8)
-> 다시 open 상태로 즉각 변경됨

2024-06-24 16:04 UTC, mingmingmon reviewed
제가 개념적인 부분이 부족한 것 같아 질문드립니다!

스케쥴링 로직과 transaction 어노테이션의 혼용이 문제가 되는 이유를 더 구체적으로 설명해주실 수 있나요? 준영속성 관련된 이야기도 해주시면 이해하는데 도움이 될 것 같습니다!

2024-06-24 16:21 UTC, limehee requested changes

2024-06-24 16:21 UTC, limehee commented on src/main/java/page/clab/api/domain/recruitment/application/RecruitmentService.java
> +                    ? RecruitmentStatus.CLOSED : RecruitmentStatus.OPEN;
중첩 삼항 연산자 코드는 사용하는 방법에 따라 가독성을 높일 수도 있겠지만, 호불호가 많이 갈리는 코드 스타일입니다.
호불호가 갈리는 코드 스타일은 프로젝트에 적합하지 않다고 판단하기에, if 조건문으로 변경하는게 더 좋지 않을까 합니다.

2024-06-24 16:21 UTC, limehee commented on src/main/java/page/clab/api/domain/recruitment/domain/Recruitment.java
> -    @Size(min = 1, message = "{size.recruitment.status}")
`messages.properties`에 유효성에 관련한 메시지를 저장하고 전달하는 방식으로 설계되어 있습니다.
`{size.recruitment.status}` 코드를 제거 또는 수정을 하게 된다면, `messages.properties`의 내용도 수정되어야 합니다.

2024-06-24 16:21 UTC, limehee commented on src/main/java/page/clab/api/domain/recruitment/domain/Recruitment.java
> +    private RecruitmentStatus status;
모집 공고의 상태를 Enum으로 정형화한 점은 좋으나, 이러한 변경은 프론트엔드와의 협의가 필요합니다.
제가 들은 얘기는 없어서, 사전 협의가 되었는지 확인차 코멘트 남깁니다.

2024-06-24 16:21 UTC, limehee commented on src/main/java/page/clab/api/global/config/TransactionConfig.java
> +    public TransactionDefinition transactionDefinition(){
()와 { 사이에 공백 추가 부탁드립니다.

2024-06-24 16:21 UTC, limehee commented on src/main/java/page/clab/api/domain/recruitment/application/RecruitmentService.java
> +        updateRecruitmentStatusByRecruitment(recruitment);
모집 공고가 수정된 경우에도 모집 시작/종료일이 변경될 수 있기 때문에 상태 검사를 해야된다고 생각합니다.

2024-06-25 02:00 UTC, SongJaeHoonn commented
@mingmingmon 

엔티티의 준영속 상태는, 해당 객체가 이미 DB에 한 번 저장되어 다시 나와 JPA의 영속성 컨텍스트가 더 이상 관리하지 않는 상태를 말합니다.

해당 작업을 하다가, 스케줄링이 걸린 메소드에서 트랜잭션이 제대로 적용되지 않아, 코드 상에서는 모집 상태가 변경되지만 실제로는 커밋이 되지 않아 DB에 업데이트된 사항이 적용되지 않는 문제가 있었습니다.

오랫동안 고민해서 찾아보니, 스프링의 스케줄러를 이용한 작업에서 트랜잭션 매니저와 관련된 문제(@EnableTransactionManagement를 통해서 DataSourceTransactionManager로 구성된 경우 하이버네이트의 begin 메소드가 AbstractTransactionImpl을 부르지 않는 문제) 때문에 트랜잭션 처리가 불가능하다는 것을 알아냈고, 

따라서 트랜잭션 매니저를 직접 이용해서 커밋과 머지를 직접 하는 방식으로 구현했습니다.

2024-06-25 02:03 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/recruitment/application/RecruitmentService.java
> +                    ? RecruitmentStatus.CLOSED : RecruitmentStatus.OPEN;
if문을 사용하는 것이 코드가 조금 더 길어질 것 같아 중첩 삼항 연산자를 선택했던 것인데, 
생각해보니 타인을 생각하지 않고 저만 생각했던 것 같습니다!
확실히 협업이 중요한 프로젝트 상에서 호불호가 갈리는 스타일을 사용하지 않는게 좋을 것 같네요.
코드는 변경하도록 하겠습니다.

2024-06-25 02:05 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/recruitment/domain/Recruitment.java
> -    @Size(min = 1, message = "{size.recruitment.status}")
`messages.properties` 에 사용하지 않는 코드들이 많아서 그냥 놔둬도 되겠다고 생각했었는데, 
필드의 타입이 완전히 바뀌고 size가 절대 사용되지 않는 시점에서 삭제 하는게 맞는 것 같네요! 조언 감사합니다
해당 코드는 수정하도록 하겠습니다.

2024-06-25 02:06 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/recruitment/domain/Recruitment.java
> +    private RecruitmentStatus status;
협업 경험이 별로 없어서 이것도 저만 생각했던 것 같네요.. 죄송합니다 
빠르게 협의 후 수정 할 부분이 있으면 수정하도록 하겠습니다.

2024-06-25 02:14 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/recruitment/application/RecruitmentService.java
> +        updateRecruitmentStatusByRecruitment(recruitment);
모집 상태를 변경하는 메소드가 매 시 0분마다 스케줄링되어 자동으로 호출되기 때문에, 모집 시작/종료일이 변경되더라도 자동으로 상태 검사가 진행되고 있습니다.

2024-06-25 02:32 UTC, limehee commented on src/main/java/page/clab/api/domain/recruitment/application/RecruitmentService.java
> +        updateRecruitmentStatusByRecruitment(recruitment);
`updateRecruitment()` 메소드에서 필요할 것으로 여겨집니다. 모집이 이미 끝난 시점에서 연장을 하게 되었을 경우에, 자정이 지나면 `모집 중`으로 상태가 바뀌겠지만, 그전까지는 `모집 종료` 상태로 남아있을 겁니다.

2024-06-25 02:35 UTC, limehee commented on src/main/java/page/clab/api/domain/recruitment/application/RecruitmentService.java
> +        updateRecruitmentStatusByRecruitment(recruitment);
모집 공고를 새로 올렸을 때 모집일 검사를 통해 진행 상태를 나타내듯이, `startDate`와 `endDate`를 다루는 `updateRecruitment()`에서도 다시 한 번 모집일 검사를 거쳐야 즉각적으로 모집 상태를 나타낼 수 있을 거라 여겨집니다.

2024-06-25 04:42 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/recruitment/application/RecruitmentService.java
> +        updateRecruitmentStatusByRecruitment(recruitment);
`startDate`와 `endDate`가 변경된 직후 `updateRecruitmentStatus()`가 자동으로 호출되기 전까지 이전 상태로 남아있을 것이고, 그에 따라 변경 후 즉각적인 DB반영을 기대할 수 없다는 말씀으로 이해했습니다.
모집 공고를 새로 올렸을 때에는 생성 당시 기본 status가 없어서 `updateRecruitmentStatusByRecruitment()`를 호출해서 즉각적인 반영을 했던 것이었는데, 모집 공고 수정에도 같은 이슈가 있을지는 미처 생각하지 못했네요.
코드 수정하도록 하겠습니다 감사합니다!

2024-06-25 12:37 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/recruitment/application/RecruitmentService.java
> +        updateRecruitmentStatusByRecruitment(recruitment);
+ 수정 후 스크린샷도 첨부했습니다.

2024-06-25 14:42 UTC, limehee approved these changes

2024-06-25 14:42 UTC, merged