게시글에 이모지로 반응하기 기능추가
KGU-C-Lab/clab-server pull request #396
Opened 2024-06-27 16:18 UTC by mingmingmon

## Summary

> #395 

게시글에 이모지로 감정표현을 할 수 있도록 필요한 API와 메소드를 작성했습니다.

## Tasks

 1. 게시글 좋아요 기능 제거
 2. 게시글에 이모지 등록/취소 API 작성
 3. 게시글에 달린 이모지 조회 메소드 작성 후 게시글 상세조회 시 함께 반환
 4. 소프트 딜리트와 하드 딜리트의 혼용
 5. 인덱싱을 활용한 DB 최적화

- 2번 테스크에 대해서 boardId, memeberId, emoji가 일치하는 레코드가 존재하면 isDeleted의 값을 반전시키고, deletedAt을 재설정하는 로직을 사용했습니다.

- 이는 4번과 연결되어 기존의 소프트 딜리트 정책을 가져가면서 하드 딜리트를 접목했습니다. 스케쥴링을 통해서 deletedAt이 7일이 초과된 경우에는 실제로 DB에서 레코드를 삭제해 DB 부담을 줄였습니다.

- 5번 테스크는 BoardEmoji 테이블에 두 개의 인덱스 (boardId, memberId, emoji)와 (boardId, emoji)를 두어서 조회 성능을 향상시켰습니다.

## ETC

```
-- 기존 좋아요 관련 테이블 삭제
DROP TABLE IF EXISTS BoardLike;

-- 기존 "like" 칼럼을 삭제
ALTER TABLE Board DROP COLUMN `like`;
```

## Screenshot
삭제된 경우 / 삭제되지 않은 경우 isDeleted와 deletedAt의 칼럼정보
![image](https://github.com/KGU-C-Lab/clab-server/assets/96719969/99abcd68-0cd5-4681-9e21-cf54484729b6)

특정 boardId로 게시글 상세조회 시 게시글 정보와 함께 이모지 반응 정보를 함께 전달하도록 함
![image](https://github.com/KGU-C-Lab/clab-server/assets/96719969/854b278d-4d84-4f78-b036-0d564572a0f0)

2024-06-28 00:15 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/board/domain/BoardEmoji.java
> +@SQLDelete(sql = "UPDATE board SET is_deleted = true WHERE id = ?")
게시판의 이모지의 소프트 딜리트를 통해 얻는 이점이 무엇인지 궁금합니다.
이모지 삭제 시 소프트 딜리트를 통해 DB에 남겨 둘 이유가 있는지 잘 모르겠습니다.
저는 소프트 딜리트를 적용하는 이유가 "복원" 때문이라고 생각하는데, 이모지가 그정도로 중요한 데이터는 아닌 것 같아서, 오히려 컬럼이 하나 더 추가되어 select 검색 시에 불필요한 조회가 추가되지 않나요?

2024-06-28 00:50 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/board/domain/BoardEmoji.java
> +@SQLDelete(sql = "UPDATE board SET is_deleted = true WHERE id = ?")
저도 게시판 이모지에 소프트 딜리트를 적용하는게 좋을까? 라는 생각을 했는데요. 제가 나름대로 내린 결론은 다음과 같습니다.

1. 사용자가 게시글을 확인하고 초반에 감정표현하는 시기는 여러 개의 이모지를 클릭하고 취소하는 동작을 할 거라고 예상했습니다. 만약 하드 딜리트만 적용한다면 이런 동작에서 여러 개의 레코드가 추가, 삭제 되는 동작 때문에 부하가 클 것이라고 생각했어요.
-> 이 부분에서 isDeleted와 DeletedAt 칼럼은 인덱싱에 포함되지 않아서 UPDATE쿼리가 더 빠르다고 생각했습니다. 하드 딜리트로 레코드를 삭제하고 나중에 또 추가한다면 인덱싱이 적용된 memberId, boardId, emoji에 추가 인덱스 INSERT와 DELETE문이 필요해서 오래 걸릴거라고 생각했습니다.
2. 따라서 게시글을 확인하고 감정표현 데이터가 많이 변화하는 초반에는 소프트 딜리트로 isDeleted 칼럼과 DeletedAt 칼럼을 수정하는 동작을 수행하고자 했습니다.
3. 그리고 스케쥴링으로 7일 보다 더 오래된 소프트 딜리트는 하드 딜리트로 삭제하는 과정을 거칩니다.

다른 domain에서는 소프트 딜리트를 사용하는 이유가 **복원**에 있었지만, BoardEmoji에서는 게시글 확인 후 초반 사용자의 빈번한 이모지 등록/취소 작업을 고려해서 **DB 최적화**의 의도로 사용해보았습니다.

DB 최적화 관련해서 처음 작업해보는 것이라 제 설계가 비효율적일 수도 있어요! 하드 딜리트 단독으로 사용하는 것이 더 좋을 것 같다면, 조금 더 이야기 한 뒤에 수정하도록 하겠습니다. 편하게 의견 주세요!

2024-06-28 01:15 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/board/domain/BoardEmoji.java
> +@SQLDelete(sql = "UPDATE board SET is_deleted = true WHERE id = ?")
사용자의 행동 패턴에 대해서는 생각하지 못했네요. 
적어주신 내용을 읽어보니 DB 최적화의 의도로 소프트 딜리트를 사용하는 방법도 되게 좋은 방법인 것 같습니다.
해당 방법을 사용하고, 차차 DB 최적화를 어떻게 더 효율적으로 할 수 있을 지 생각하며 적용해나가도 될 것 같네요.

2024-06-28 01:42 UTC, SongJaeHoonn commented
올려주신 코드를 보니, 한 사람이 한 게시글에 여러 개의 이모지를 추가 할 수 있는 것 같은데, 도배 등의 문제가 생길 것 같아 따로 이것을 방지할 코드가 있는건가요?
아니면 제가 코드를 잘못 이해하고 있는건지 궁금해서 여쭤봤습니다!

2024-06-28 02:06 UTC, mingmingmon commented
> 올려주신 코드를 보니, 한 사람이 한 게시글에 여러 개의 이모지를 추가 할 수 있는 것 같은데, 도배 등의 문제가 생길 것 같아 따로 이것을 방지할 코드가 있는건가요? 아니면 제가 코드를 잘못 이해하고 있는건지 궁금해서 여쭤봤습니다!

깃허브 감정표현처럼 한 사람이 한 게시글에 여러 개의 이모지를 달 수 있어요! 

지금 "emoji"를 String으로 받아오기 때문에 사용자가 여러 개의 이모지를 마음대로 추가할 수 있는 건 아닌가 싶으신거죠?

"emoji"에 들어올 수 있는 유니코드는 프론트에서 설정한 몇 개의 이모지 리스트 중 하나 일 것 같습니다. 아래 사진처럼 프론트팀에서 이모지 몇 개를 선정할 것 같아요. 
![image](https://github.com/KGU-C-Lab/clab-server/assets/96719969/2dc42cf5-717d-49d8-98ff-cbdc674472ad)

정리하자면
1. 현재 한 사람이 한 게시글에 여러 이모지를 클릭할 수 있도록 하고 있는 게 맞습니다. 
2. 도배 관련 문제는 프론트에서 설정한 이모지만 클릭할 수 있어서 백엔드에서 따로 금지하는 코드는 없습니다. 
3. 또한 아직 프론트에서 무슨 이모지를 사용하는지 전달 받은 게 없어서 이 부분은 나중에 한 번 프론트 팀과 이야기 해보도록 할게요!

2024-06-28 03:50 UTC, limehee commented
> 2. 도배 관련 문제는 프론트에서 설정한 이모지만 클릭할 수 있어서 백엔드에서 따로 금지하는 코드는 없습니다.
> 3. 또한 아직 프론트에서 무슨 이모지를 사용하는지 전달 받은 게 없어서 이 부분은 나중에 한 번 프론트 팀과 이야기 해보도록 할게요!

예정된 작업으로 보이긴 하나, 조금 다른 측면에서 피드백 드립니다.

프론트엔드에서 정해진 이모지 코드로 API 요청을 보낸다 하더라도, RESTful API의 특성상 엔드포인트가 노출되기 때문에 사용자가 얼마든지 정해지지 않은 이외의 값을 보낼 수 있습니다. 따라서 프론트엔드에서 제한을 두는 것도 중요하지만, 백엔드에서도 추가적인 검증 단계를 마련하는 것이 필요합니다. 예를 들어, 백엔드에서 Enum 또는 문자열 검사를 통해 요청값을 검증하는 단계가 필요합니다. 입력값을 검증하지 않고 모든 데이터를 저장하면 시스템 성능 저하, 비즈니스 로직 오류, 사용자 신뢰 저하 등의 문제가 발생할 수 있습니다.

프론트 팀과 논의해서 어떤 이모지를 사용할 지 정하고, Enum으로 변경하길 바랍니다.

2024-06-28 04:40 UTC, limehee requested changes

2024-06-28 04:40 UTC, limehee commented on src/main/java/page/clab/api/domain/board/application/BoardService.java
> +        return BoardDetailsResponseDto.toDto(board, currentMemberInfo, isOwner, boardEmojiCountResponseDtoList);
`getBoardDetails()`에서 memberId 외의 값을 사용하지 않고 있습니다.
`MemberDetailedInfoDto`는 memberId 외에도 여러 가지 상세 정보를 포함하고 있기 때문에, 이 객체를 전달하면 불필요한 데이터가 포함되어 데이터 전달 시 오버헤드가 발생할 수 있습니다.

또한, `MemberDetailedInfoDto` 객체는 많은 값을 포함하고 있기 때문에 메모리 사용량이 증가할 수 있습니다. 불필요한 데이터를 메모리에 로드하고 유지하는 것은 메모리 효율성을 떨어뜨리고, 메모리 자원을 낭비하게 됩니다.

따라서, 필요한 값만 전달하는 것이 효율적입니다. `getCurrentMemberId()`를 사용하면 memberId만 전달하여 데이터 오버헤드와 메모리 사용량을 줄일 수 있습니다.

2024-06-28 04:40 UTC, limehee commented on src/main/java/page/clab/api/domain/board/application/BoardService.java
>          }
```
BoardEmoji boardEmoji = boardEmojiRepository.findByBoardIdAndMemberIdAndEmoji(boardId, memberId, emoji)
        .map(existingEmoji -> {
            existingEmoji.toggleIsDeletedStatus();
            return existingEmoji;
        })
        .orElseGet(() -> BoardEmoji.create(memberId, boardId, emoji));
```

Optional로 안전하게 처리한 점이 인상적입니다. 그러나 해당 로직을 람다식을 이용해 처리하면 더 간단하고 안정적으로 구현할 수 있습니다.

2024-06-28 04:40 UTC, limehee commented on src/main/java/page/clab/api/domain/board/application/BoardService.java
>          }
`@Transactional`도 붙여주세요.
JPA Auditing을 사용하여 엔티티의 생성 및 수정 시간을 자동으로 기록하고 있는데, 트랜잭션 설정을 안해주면 갱신되지 않습니다.

2024-06-28 04:40 UTC, limehee commented on src/main/java/page/clab/api/domain/board/dao/BoardEmojiRepository.java
> +    @Query("SELECT new page.clab.api.domain.board.dto.response.BoardEmojiCountResponseDto(b.emoji, COUNT(b), " +
도메인 주도 설계에서는 응용 계층과 도메인 계층의 역할을 명확히 분리하는 것이 중요합니다. JPQL에서 직접 DTO를 생성하는 것보다는 쿼리 결과를 응용 계층에서 DTO로 변환하는 것이 더 좋습니다.

2024-06-28 04:40 UTC, limehee commented on src/main/java/page/clab/api/domain/board/domain/BoardEmoji.java
> +    }
```
public void toggleIsDeletedStatus() {
    this.isDeleted = !this.isDeleted;
    this.deletedAt = this.isDeleted ? LocalDateTime.now() : null;
}
```

이렇게 표현하면 간결하면서도 delete되었을 때 시간을 기록한다는 의미를 더 명확하게 표현할 수 있습니다.

2024-06-28 05:23 UTC, limehee commented on src/main/java/page/clab/api/domain/board/application/BoardService.java
> +        return BoardDetailsResponseDto.toDto(board, currentMemberInfo, isOwner, boardEmojiCountResponseDtoList);
BoardDetailsResponseDto 변환에서 `MemberDetailedInfoDto`의 정보가 필요했네요. 잘못된 피드백입니다. 죄송합니다.

2024-06-28 11:37 UTC, mingmingmon commented
아래의 사진을 요약하자면 숫자 1은 이모지로 사용될 수 없고, 
단일 이모지와 복합 이모지들은 잘 실행됨을 확인할 수 있습니다.

![image](https://github.com/KGU-C-Lab/clab-server/assets/96719969/ea7e8153-a675-4442-893f-0e9896c74e4b)
![image](https://github.com/KGU-C-Lab/clab-server/assets/96719969/59bce637-1ed4-4daa-8bc7-d8d5eb11d189)
![image](https://github.com/KGU-C-Lab/clab-server/assets/96719969/3653c33c-7c63-4e09-bba6-1affbbec798e)

![image](https://github.com/KGU-C-Lab/clab-server/assets/96719969/1f8b2e8f-9f45-4766-bcfe-41084bdcd420)
![image](https://github.com/KGU-C-Lab/clab-server/assets/96719969/121a297d-7db6-40ff-9939-2c20388f99b9)
![image](https://github.com/KGU-C-Lab/clab-server/assets/96719969/d7785f0f-4051-4822-974d-01e9a308f434)

2024-06-29 04:38 UTC, limehee approved these changes

2024-06-29 07:25 UTC, merged