스웨거 접근 시 슬랙 알림 전송 로직 작성 완료
KGU-C-Lab/clab-server pull request #398
Opened 2024-07-04 11:22 UTC by SongJaeHoonn

## Summary

> #397 

누구든지 Core-Team의 Swagger에 접근하면 팀 내 슬랙 채널에 알림이 가도록 하는 로직을 구현했습니다.
알림의 내용은 스웨거 접근 여부와 접속 실패, 접속 성공으로 나뉘게 됩니다.

## Tasks

- Swagger 접근 시 슬랙에 알림이 가도록 하는 로직 구현

## ETC

스웨거와 같은 api 문서들을 관리하는 필터를 따로 분리하려고 했으나, 기존 인증 필터들에 스웨거 관련 로직이 강하게 결합되어 있어 인증 부분은 원래의 인증 필터에서 처리하는 것이 낫다고 판단했습니다.
다만 이 과정에서 슬랙에 알림을 가도록 하는 때가 스웨거 로그인 이후이므로, 각각의 인증이 완료되자마자 슬랙 알림을 바로 보내는 것이 낫다고 판단하여 굳이 Api 문서 관리 필터를 만들지 않았습니다.  

## Screenshot

![스크린샷 2024-07-04 201638](https://github.com/KGU-C-Lab/clab-server/assets/128021502/b2326dd8-0441-4114-8c60-077c4b2d61fc)

![스크린샷 2024-07-04 201618](https://github.com/KGU-C-Lab/clab-server/assets/128021502/ac0b04b4-684c-43c4-ab52-f1ea621a1c62)

2024-07-04 14:12 UTC, limehee requested changes

2024-07-04 14:12 UTC, limehee commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +        }
API 문서의 URL은 노출되지 않아야 합니다. API 문서가 외부에 공개될 경우, 다음의 문제가 발생할 수 있습니다.
- 엔드포인트 URL이 노출되면 공격자는 특정 엔드포인트를 대상으로 공격을 시도할 가능성이 커집니다. 예를 들어, 권한이 없는 사용자나 애플리케이션이 해당 엔드포인트에 접근할 수 있습니다.
- 민감한 데이터나 기능에 접근할 수 있는 경로를 공개함으로써, 비인가된 사용자가 시스템에 접근하여 데이터를 훼손하거나 도용할 위험이 증가합니다.

2024-07-04 14:12 UTC, limehee commented on src/main/java/page/clab/api/global/auth/filter/JwtAuthenticationFilter.java
> +            }
해당 부분에 이와 같은 코드가 추가되게 된 이유를 여쭙고 싶습니다.
토큰을 인증하는 부분에서 서버 오류에 대한 탐지가 필요한 이유에 대한 설명 부탁드립니다.

현재 권한이 없는 엔드포인트에 접근하거나 비정상적인 접근이 탐지될 경우 401, 403 등의 오류를 발생시키고 있으며, 해당 부분에서 토큰 인증에 실패한 경우 상태 코드 401을 클라이언트에게 전달합니다.

2024-07-04 14:12 UTC, limehee commented on src/main/java/page/clab/api/global/common/slack/application/SlackService.java
> +    }
API 문서에 대한 접근은 보안 알림에 해당됩니다. sendSecurityAlertNotification()를 이용해야 합니다.

2024-07-04 14:12 UTC, limehee commented on src/main/java/page/clab/api/global/common/slack/domain/GeneralAlertType.java
> +    SWAGGER_ACCESS("Swagger 접근", "Swagger accessed."),
API 문서에 대한 접근은 보안 알림에 해당되므로, SecurityAlertType으로 이동되어야 합니다.

2024-07-04 14:31 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/auth/filter/JwtAuthenticationFilter.java
> +            }
![image](https://github.com/KGU-C-Lab/clab-server/assets/128021502/e3f2f4e2-4a4f-42d4-a561-1974f572eaf7)

위 사진은, Api 문서의 URL에 접속 후 잘못된 로그인 정보를 입력하여 로그인 실패 시 나오는 로그입니다. 한 번의 로그인 실패 시 세 번의 요청이 서버로 들어오므로 가장 처음 오는 요청인 500 에러를 만날 시에만 접근 실패 알람이 가도록 기획했습니다. 제 로컬 테스트 환경에서는 로그인 실패 시 서버 에러가 뜨는데 원래는 다르게 작동이 되는건가요?

2024-07-04 14:33 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +        }
조언 감사합니다! URL을 감추고, 다른 방식으로 해당 URL을 사용하도록 변경하겠습니다.

2024-07-04 14:35 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/common/slack/application/SlackService.java
> +    }
변경하도록 하겠습니다!

2024-07-04 16:02 UTC, limehee commented on src/main/java/page/clab/api/global/auth/filter/JwtAuthenticationFilter.java
> +            }
`/error`로 판단하기에는 API 문서 접근 외에도 발생할 수 있는 경우의 수가 너무 많습니다. 해당 방법보다는 인증에 실패했을 경우를 캐치하여 알림을 보내도록 하는 편이 더 낫다고 생각합니다.

2024-07-04 16:05 UTC, limehee commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +        }
`@Value` 어노테이션을 이용하면 profile에 지정된 프로퍼티를 가져올 수 있습니다. 참고하시면 좋을 것 같아요.

2024-07-04 22:56 UTC, mingmingmon commented on src/main/java/page/clab/api/global/config/SecurityConfig.java
> +                .addFilterBefore(
해당 커밋까지는 ApiDocsAuthenticationFilter로 필터 분리를 시도해주셨는데, 여기서 어떤 어려움 때문에 다시 인증필터와 API 문서 필터를 합치게 된 건지 조금 더 구체적으로 설명해주실 수 있나요?

2024-07-05 00:44 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/config/SecurityConfig.java
> +                .addFilterBefore(
필터 체이닝 구조상 요청이 들어오면 `SecurityConfig`에 정해둔 순서대로 필터를 거쳐가는데, 요청이 들어온 path가 Swagger의 path인지 확인하는 것은 인증 전에 해야하고, 슬랙 알림을 보내는 것은 인증 후에 해야 하므로 `ApiDocsAuthenticationFilter`에서 스웨거에 관련한 모든 것을 담당하려면 해당 필터에 인증과 알림을 모두 담아야 합니다.
그렇게 되면 기존 인증 필터들과 중복되는 부분도 정말 많아지고, 오히려 더 복잡해진다는 생각이 들어 필터를 다시 합치게 되었습니다.

2024-07-05 00:48 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/auth/filter/JwtAuthenticationFilter.java
> +            }
Swagger 인증이 아닌 다른 인증이 필요한 부분에 대해서도 error가 발생할 수 있다는 걸 빼고 생각했었네요. 다시 생각해보겠습니다.

2024-07-07 13:57 UTC, mingmingmon approved these changes

2024-07-07 14:38 UTC, limehee commented on src/main/java/page/clab/api/global/common/slack/domain/SecurityAlertType.java
> +    SWAGGER_ACCESS("Swagger 접근", "Swagger accessed."),
Swagger 접근이라는 표현도 좋지만, 더 명확하게 "API 문서 접근" 이라는 표현이 더 괜찮을 것 같아요.

2024-07-07 14:38 UTC, limehee commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +    }
추가 메시지 내용을 좀 더 자세하게 작성할 필요가 있어보입니다.

2024-07-07 14:38 UTC, limehee commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +    private String swaggerEndpoint;
현재 작업이 API 문서 접근으로만 되어있는데, Whitelist로 처리되는 엔드포인트를 모두 관리하도록 확장하는 방향도 괜찮아 보입니다. Whitelist로 관리되는 엔드포인트는 모두 보안과 관련되어있을 뿐더러, 지난번 리팩토링에서 잘못 처리한 부분이 있어서 SwaggerUtil에서 Whitelist 엔드포인트를 모두 검사하고 있어서 조금만 수정하면 가능합니다.

1. SwaggerUtil을 WhitelistUtil 등으로 변경
2. security.whitelist 세분화 및 접근한 엔드포인트가 어떤 서비스에 대한 것인지 식별 가능하도록 리팩토링
3. 엔드포인트에 따라 접근한 서비스를 식별하여 유동적으로 슬랙 보안 경고 메시지를 전송

이렇게 하면 조금의 수정으로 API 문서 외에도 다양한 서비스를 관리할 수 있겠네요.

2024-07-07 14:38 UTC, limehee commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +        }
```java
try {
    authentication = getAuthenticationManager().authenticate(authRequest);
    if (authentication == null) {
        ResponseUtil.sendErrorResponse(response, HttpServletResponse.SC_UNAUTHORIZED);
        return false;
    }
    SecurityContextHolder.getContext().setAuthentication(authentication);
    
    String path = request.getRequestURI();
    if (path.equals(swaggerEndpoint)) {
        sendApiDocsSuccessAlertSlackMessage(request);
    }
} catch (BadCredentialsException e) {
    sendApiDocsFailureAlertSlackMessage(request);
    ResponseUtil.sendErrorResponse(response, HttpServletResponse.SC_UNAUTHORIZED);
    return false;
}

```
이렇게 작성하면 로직이 더 깔끔해질 것 같네요.

2024-07-08 01:47 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +    private String swaggerEndpoint;
SwaggerUtil에서 Whitelist를 전부 검사하고 있으니, 기존의 SwaggerUtil을 그냥 WhitelistUtil로 변경해도 상관 없다는 말씀으로 이해가 됩니다. 그렇다면 SwaggerUtil이 아닌 WhilelistUtil로 변경이 되므로 범용성이 늘어나는 것이기 때문에 기존의 `isSwaggerRequest` 도 WhitelistUtil에서 처리해도 되는건가요?

2024-07-08 01:53 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +        }
정돈된 코드까지 직접 보여주셔서 감사합니다! 앞으로 깔끔한 코드 작성에 대해서 걱정하시지 않도록 더욱 노력하겠습니다.

2024-07-08 01:59 UTC, limehee commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +    private String swaggerEndpoint;
Whitelist로 분류된 엔드포인트를 세분화해서 api 문서, 액추에이터 등으로 분류해놓으면 조금의 수정으로 범용성있는 서비스를 만들 수 있고, `isSwaggerRequest`, `isActuatorRequest`, `isWhitelistRequest` 등으로 계속해서 확장 가능합니다.

그리고 현재 `isSwaggerRequest`에서 검사하고 있는 항목을 추적해보면, API 문서 외의 엔드포인트도 섞여있어요.

2024-07-09 10:49 UTC, mingmingmon commented on src/main/java/page/clab/api/global/util/WhitelistUtil.java
> +    }
WhitelistPatternsProperties에서 정의된 Map으로 api-docs 관련 경로인지, actuator 관련 경로인지 구분하는 것이 흥미로웠습니다. @ConfigurationProperties를 통해 yml의 patterns 속성을 Map으로 저장하신 것 같습니다. 

혹시, 해당 부분을 Map으로 저장해놓는게 아니라 각 경로별로 @ConfigurationProperties를 나눠서 직접 등록하는 방법은 어떠신가요?

1. 지금은 하위의 모든 경로가 슬랙 알림으로 다 사용되고 있지만, 슬랙 알림에 나중에 포함되지 않는 경로가 생길 경우 불필요한 프로퍼티도 map에 저장될 것 같습니다.
2. 구분해서 변수로 저장해놓으면 map에서 꺼내지 않고, 사용할 수도 있으니 좀 더 깔끔한 코드가 될 수 있을 것 같습니다.

저 또한 필터와 보안 관련 부분은 다소 미숙해서 맞는 피드백인지 모르겠지만, 한 번 고려해주시면 감사하겠습니다!

2024-07-09 11:17 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/util/WhitelistUtil.java
> +    }
Map으로 경로를 모두 저장하지 않고, 단순 배열로 분리해 책임을 명확하게 따로 처리 하는 것이 추후에 새로 생길 경로나, 해당 경로 관리에 좋은 아이디어인 것 같습니다! 좋은 의견 감사합니다. 반영하도록 하겠습니다.

2024-07-09 11:32 UTC, limehee requested changes

2024-07-09 11:32 UTC, limehee commented on src/main/java/page/clab/api/global/config/WhitelistPatternsProperties.java
> +    private Map<String, String[]> patterns;
Map으로 저장하는 방식보다는, 서비스별(API Docs, Actuator 등)로 구분하여 List 또는 String[] 자료형에 저장하는게 가독성이나 유지보수성 측면에서 좋아보입니다.

2024-07-09 11:32 UTC, limehee commented on src/main/java/page/clab/api/global/util/WhitelistUtil.java
> +    }
패턴 검사 로직이 반복적으로 사용되고 있습니다. 중복 코드를 추출하여 다음과 같이 수정할 수 있습니다.

```java
    public static boolean isSwaggerRequest(String path) {
        return isPatternMatch(path, swaggerPatterns);
    }

    public static boolean isActuatorRequest(String path) {
        return isPatternMatch(path, actuatorPatterns);
    }

    public static boolean isWhitelistRequest(String path) {
        return isPatternMatch(path, whitelistPatterns);
    }

    private static boolean isPatternMatch(String path, String[] patterns) {
        for (String pattern : patterns) {
            if (Pattern.compile(pattern).matcher(path).find()) {
                return true;
            }
        }
        return false;
    }
```

2024-07-09 11:32 UTC, limehee commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +            slackService.sendSecurityAlertNotification(request, SecurityAlertType.API_DOCS_ACCESS,"API 문서 접근 성공");
다른 알림이랑 형식 맞춰서 "___ 접근이 허가되었습니다.", "___ 접근이 거부되었습니다."로 메시지 보내는게 더 좋아보입니다.

2024-07-09 11:32 UTC, limehee commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +            }
`getAuthenticationManager().authenticate(authRequest);`에서 인증이 실패하면, `BadCredentialsException`이 발생하므로, Authentication 객체를 null로 초기화를 하지 않아도 되며, 해당 조건문은 작동하지 않습니다.

2024-07-09 11:32 UTC, limehee commented on src/main/java/page/clab/api/global/config/ApiDocsConfig.java
> +}
API Docs의 엔드포인트는 Whitelist로 관리되고 있기 때문에, ApiDocsConfig를 별도로 관리할 필요는 없어보입니다.

2024-07-09 11:32 UTC, limehee commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +    }
`WhitelistPatternsProperties`는 프로퍼티를 한 곳에서 모아 관리하기 위한 클래스이고, 관련 기능을 `WhitelistUtil`에서 관리하고 있습니다. 따라서, `isApiDocsPath`, `isActuatorPath`는 Util의 메소드 기능으로 옮겨서 사용하는 편이 더 옳다고 여겨집니다.

2024-07-09 11:32 UTC, limehee commented on src/main/java/page/clab/api/global/common/slack/domain/SecurityAlertType.java
> +    ACTUATOR_ACCESS("Actuator 접근", "Actuator accessed."),
```java
API_DOCS_ACCESS("API 문서 접근", "API documentation access attempt."),
ACTUATOR_ACCESS("Actuator 접근", "Actuator endpoint access attempt."),
```
이런 식의 문구가 보안 문제를 경고하는 느낌이 담겨서 더 좋을 것 같아요. 반영은 선택입니다.

2024-07-09 11:41 UTC, limehee commented on src/main/java/page/clab/api/global/util/WhitelistUtil.java
> +    }
> WhitelistPatternsProperties에서 정의된 Map으로 api-docs 관련 경로인지, actuator 관련 경로인지 구분하는 것이 흥미로웠습니다. @ConfigurationProperties를 통해 yml의 patterns 속성을 Map으로 저장하신 것 같습니다.
> 
> 혹시, 해당 부분을 Map으로 저장해놓는게 아니라 각 경로별로 @ConfigurationProperties를 나눠서 직접 등록하는 방법은 어떠신가요?
> 
> 1. 지금은 하위의 모든 경로가 슬랙 알림으로 다 사용되고 있지만, 슬랙 알림에 나중에 포함되지 않는 경로가 생길 경우 불필요한 프로퍼티도 map에 저장될 것 같습니다.
> 2. 구분해서 변수로 저장해놓으면 map에서 꺼내지 않고, 사용할 수도 있으니 좀 더 깔끔한 코드가 될 수 있을 것 같습니다.
> 
> 저 또한 필터와 보안 관련 부분은 다소 미숙해서 맞는 피드백인지 모르겠지만, 한 번 고려해주시면 감사하겠습니다!

- 여러 개의 @ConfigurationProperties 클래스로 나누면 각 경로별 설정이 흩어지게 되어, 전체적으로 관리하기 어렵고 응집도가 떨어집니다. 하나의 클래스에서 List<String> 또는 String[] 형식으로 각각의 경로를 저장하면, 설정을 한 곳에서 일관되게 관리할 수 있어 유지보수가 용이합니다.
- 여러 개의 @ConfigurationProperties 클래스를 사용하면 새로운 경로가 추가될 때마다 새로운 클래스를 추가하고 관련된 설정을 모두 업데이트해야 하는 번거로움이 발생합니다.
- 현재 구조에서는 WhitelistPatternsProperties 클래스가 "화이트리스트 패턴의 관리"라는 하나의 책임을 가지고 있습니다.
여러 개의 @ConfigurationProperties 클래스로 나누면 클래스가 경로별로 분리되어 각각의 책임이 모호해질 수 있습니다.

위의 이유로 @ConfigurationProperties 클래스를 나누어 관리하는 것을 저는 반대합니다. 제가 잘못 이해하고 있거나, 추가적인 의견 있으면 코멘트 부탁드립니다.

2024-07-09 11:56 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/config/ApiDocsConfig.java
> +}
저도 이 부분에 대해서 많이 고민했었습니다. 이 고민 당시 제 생각에 대해 말씀드리겠습니다.
1. 스웨거 접속에 성공 시 `/swagger-ui/index.html`, `/swagger-ui/index.css`, `/swagger-ui/swagger-initializer.js` 등, 많은 수의 요청이 동시에 들어오고, 각각의 요청마다 인증하기 때문에 스웨거 알림이 각 요청마다 엄청나게 많이 전송되는 이슈가 있었습니다.
따라서 , 그 요청을 대표하는 정확한 엔드포인트 하나가 필요했고, `/swagger-ui/index.html` 적당하다고 생각해 yml파일에 새로운 프로퍼티를 만들었습니다.

2. 그렇게 `CustomBasicAuthenticationFilter`에 `@Value`를 통해 주입하려고 하니, `swaggerEndpoint`에 null이 주입되는 문제가 있었습니다. 
찾아보니, CustomBasicAuthenticationFilter는 SecurityConfig에서 new로 생성이 되어 빈으로 등록이 되지 않았다는 문제가 있었습니다. (https://green-bin.tistory.com/53) 
`@Value`를 사용하는 클래스가 빈으로 등록되어있지 않다면 해당 변수에 주입이 불가능 하다는 것을 알아낸 후, swaggerEndpoint를 어떤 방식으로 가져와야 할 지 고민하다가, 결국 ApiDocsConfig를 만들게 된 것입니다.

이것 때문에 오랜 시간을 고민했어서, 다른 방식으로 swaggerEndpoint를 가져올 수 있는 방법을 알고 계신다면, 가르쳐주신다면 정말 감사할 것 같습니다!

2024-07-09 11:58 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/util/WhitelistUtil.java
> +    }
중복 로직 검사 해주셔서 감사합니다! 반영하겠습니다

2024-07-09 11:59 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +    }
너무 간단한 메소드였어서 만들고 바로 사용한다는 생각밖에 안했었네요! 조언 감사합니다

2024-07-09 12:11 UTC, limehee commented on src/main/java/page/clab/api/global/config/ApiDocsConfig.java
> +}
WhitelistUtil의 멤버 변수 swaggerPatterns에 이미 관련 엔드포인트가 담겨져서 관리되고 있습니다.
`WhitelistUtil`에 별도의 메소드를 만들어서 사용하면 새로운 Config 클래스를 생성하거나 프로퍼티를 추가하지 않아도 됩니다.

2024-07-09 12:15 UTC, mingmingmon commented on src/main/java/page/clab/api/global/util/WhitelistUtil.java
> +    }
```
@ConfigurationProperties(prefix = "test")
public class Test{
    @Value("${yml-test.first}")
    public String first;
    
    @Value("${yml-test.two}")
    public String two
}
```
이런식으로 apiDocs와 actuator를 구분하는 것을 제안 드렸던 겁니다!
"각 경로별로 @ConfigurationProperties를 사용하자"라고 한 말이 잘못됐네요.. 죄송합니다!

2024-07-09 12:16 UTC, limehee commented on src/main/java/page/clab/api/global/util/WhitelistUtil.java
> +    }
그렇군요. 제가 잘못 이해했네요. 답변 감사합니다.

2024-07-09 13:20 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/common/slack/domain/SecurityAlertType.java
> +    ACTUATOR_ACCESS("Actuator 접근", "Actuator accessed."),
피드백 해주셔서 감사합니다! 반영 완료했습니다

2024-07-09 13:21 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/config/ApiDocsConfig.java
> +}
정말 감사합니다! 해결했습니다. 피드백 사항 반영 완료했습니다.

2024-07-09 13:21 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +            }
반영 완료했습니다.

2024-07-09 13:21 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
> +            slackService.sendSecurityAlertNotification(request, SecurityAlertType.API_DOCS_ACCESS,"API 문서 접근 성공");
참고해서 반영 완료했습니다!

2024-07-09 13:22 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/config/WhitelistPatternsProperties.java
> +    private Map<String, String[]> patterns;
좋은 의견 감사합니다. 반영 완료했습니다.

2024-07-09 13:23 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/util/WhitelistUtil.java
> +    }
두 분이 저에게 해주신 피드백 사항이 비슷한 것 같아 코드에 반영 완료했습니다. 좋은 의견 정말 감사합니다!

2024-07-09 14:02 UTC, limehee requested changes

2024-07-09 14:14 UTC, limehee approved these changes

2024-07-09 16:50 UTC, merged